In [1]:
import pandas as pd 

# Data-cleaning 
##############################################################################

# df = pd.read_csv("US_Accidents_data.csv", index_col="Unnamed: 0")
df = pd.read_csv("US_Accidents_data.csv")

# Eliminate all rows with empty values in 3 or more columns
df = df.dropna(subset = ["ID", "Severity", "Zipcode", "Start_Time", "End_Time", "Visibility(mi)", "Weather_Condition", "Country"], thresh=8)
df = df.dropna(thresh=20)

# Eliminate all rows with distance equal to zero
df = df[df["Distance(mi)"] != 0]

# Only consider in your analysis the first 5 digits of the zip code
df["Zipcode"] = df["Zipcode"].str[:5]

# Convert string dates to pandas Timestamps
df['Start_Time'] = pd.to_datetime(df['Start_Time'])
df['End_Time'] = pd.to_datetime(df['End_Time'])

# All accicent that lasted no time 
# (The diference between End_time and Start_time is zero)
# If accicent Start_Time and End_Time are the same that equates to a diff of 0
df = df[df["Start_Time"] != df["End_Time"]]

##############################################################################


df

,Unnamed: 0,ID,Severity,Start_Time,End_Time,Distance(mi),Description,Number,Street,Side,...,Zipcode,Country,Timezone,Weather_Timestamp,Temperature(F),Humidity(%),Pressure(in),Visibility(mi),Precipitation(in),Weather_Condition
0,0,A-3,2,2016-02-08 06:15:39,2016-02-08 12:15:39,0.055,At I-71/US-50/Exit 1 - Accident.,NaN,I-75 S,R,...,45203,US,US/Eastern,2016-02-08 05:53:00,36.0,97.0,29.70,10.0,0.02,Overcast
1,1,A-7,2,2016-02-08 08:15:41,2016-02-08 14:15:41,0.227,At OH-4/Exit 54 - Accident.,NaN,I-75 S,R,...,45404,US,US/Eastern,2016-02-08 08:18:00,33.8,100.0,29.63,3.0,NaN,Mostly Cloudy
2,2,A-11,2,2016-02-08 15:43:50,2016-02-08 21:43:50,0.307,At OH-4/Paddock Rd/Exit 9 - Accident.,NaN,I-75 N,R,...,45216,US,US/Eastern,2016-02-08 15:47:00,33.8,100.0,29.66,3.0,0.03,Light Snow
3,3,A-15,3,2016-02-08 18:11:11,2016-02-09 00:11:11,0.004,At Shipley Rd - Accident.,48999.0,Titus Rd,R,...,43973,US,US/Eastern,2016-02-08 18:23:00,33.1,92.0,29.62,10.0,NaN,Mostly Cloudy
4,4,A-19,3,2016-02-08 20:13:22,2016-02-09 02:13:22,0.999,Between Weber Rd/Exit 113 and Hudson St/Exit 1...,NaN,North Fwy S,R,...,43224,US,US/Eastern,2016-02-08 20:12:00,33.8,100.0,29.63,1.0,0.00,Light Snow
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
711330,711330,A-2845323,2,2019-08-23 15:33:46,2019-08-23 16:03:05,0.320,At Friars Rd - Accident. Center lane blocked.,NaN,CA-163 S,R,...,92108,US,US/Pacific,2019-08-23 15:53:00,74.0,62.0,29.39,10.0,0.00,Fair
711331,711331,A-2845327,2,2019-08-23 16:33:31,2019-08-23 17:02:54,0.493,At Adams St - Accident.,NaN,CA-91 W,R,...,92504,US,US/Pacific,2019-08-23 16:53:00,90.0,33.0,28.93,10.0,0.00,Fair
711332,711332,A-2845331,2,2019-08-23 17:10:58,2019-08-23 17:40:28,0.356,At Tustin Ave - Accident.,NaN,Riverside Fwy E,R,...,92806,US,US/Pacific,2019-08-23 16:53:00,79.0,50.0,29.70,10.0,0.00,Fair
711333,711333,A-2845335,2,2019-08-23 17:40:12,2019-08-23 18:08:35,0.189,At Telephone Rd/Exit 65 - Accident.,NaN,El Camino Real N,R,...,93003,US,US/Pacific,2019-08-23 17:51:00,73.0,68.0,29.76,10.0,0.00,Fair
711334,711334,A-2845339,2,2019-08-23 19:11:30,2019-08-23 19:38:23,0.338,At Camino Del Rio/Mission Center Rd - Accident.,NaN,I-8 W,R,...,92108,US,US/Pacific,2019-08-23 18:53:00,70.0,73.0,29.39,10.0,0.00,Fair

In [7]:
# 1. In what month were there more accidents reported?
def da_month_with_most_accidents():
    global df
    month_list = ["January", "Feb", "March", "April", "May", "June", "July", 
        "August", "September", "October", "November", "December"]
    top_month = pd.DatetimeIndex(df['Start_Time']).month.value_counts()[:12]
    print(top_month)
    # accident_num = list(top_month.columns)
    num_accidents = top_month.tolist()
    month = top_month.index.tolist()

    month_index = month[0] - 1
    print("In " + month_list[month_index] + 
        " there were more accidents reported with a total of: " 
        + str(num_accidents[0]))
    # print(df2)
da_month_with_most_accidents()

12    106216
11     82709
10     65753
9      52111
6      42340
8      41015
2      39555
1      39058
7      37261
5      32359
4      29760
3      28010
Name: Start_Time, dtype: int64
In December there were more accidents reported with a total of: 106216

In [11]:
# 2. What is the state that had the most accidents in 2020?
def states_with_most_accidents_in_2022():
    global df
    # Create li
    year2020 = df["Start_Time"].dt.year == int(2020)

    # the total number of rows with year 2020
    # true_count = sum(year2012)
    # print(true_count)

     
    specifed_year = df[year2020]

    top_state = specifed_year["State"].value_counts()[:1]
    num_accidents = top_state.tolist()
    state = top_state.index.tolist()
    
    print(state[0] + " had the most accidents in 2020 with a total of: "
        + str(num_accidents[0]))

states_with_most_accidents_in_2022()

CA had the most accidents in 2020 with a total of: 22113

In [13]:
# 3. What is the state that had the most accidents of severity 2 in 2021?
def most_accidents_of_severity_2_state():
    global df

    # Get rows with specified year
    year2021 = df["Start_Time"].dt.year == int(2021)
    specifed_year = df[year2021]

    # Now get rows that only have severity 2
    index = specifed_year["Severity"] == int(2)
    specifed_year = specifed_year[index]

    
    # Get the top state from new dataframe
    top_state = specifed_year["State"].value_counts()[:1].index.tolist()
    print(top_state[0] + " had the most accidents of severity 2 in 2021")

    # print(specifed_year.head(15))
    # print(index.to_list())


most_accidents_of_severity_2_state()

CA had the most accidents of severity 2 in 2021

In [14]:
# 4. What severity is the most common in Virginia?
def virginia_top_severity():
    global df
    
    virginia = df["State"] == "VA"
    specified_state = df[virginia]
    
    top_serverity = specified_state["Severity"].value_counts()[:1]
    # Grab the number of times it appeared
    num_accidents = top_serverity.tolist()
    # The index of the dataframe top_state is the state name
    serverity = top_serverity.index.tolist()
    print("What severity is the most common in Virginia?")
    print("Severity: " + str(serverity[0]) + " was most common in Virginia with a total of: " 
        + str(num_accidents[0]) + " accidents")
    

virginia_top_severity()

What severity is the most common in Virginia?
Severity: 2 was most common in Virginia with a total of: 21767 accidents

In [21]:
# 5. What are the 5 cities that had the most accidents in 2019 in California?
def top_cities():
    global df

    # Only get rows that correspond to 2019
    year2019 = df["Start_Time"].dt.year == int(2019)
    specifed_year = df[year2019]
    
    # Only get rows from 2019 that invlove CA
    california = specifed_year["State"] == "CA"
    specified_state = specifed_year[california]

    top_cities = specified_state["City"].value_counts()[:5]

    print("What are the 5 cities that had the most accidents in 2019 in California?")
    print(top_cities.to_string())

top_cities()

What are the 5 cities that had the most accidents in 2019 in California?
Los Angeles    449
Sacramento     178
San Diego      178
San Jose       134
Oakland        121

In [26]:
# 6. What was the average humidity and average temperature of all accidents of severity 4 that occurred in 2021?

def avgerage_humidity_temp():
    global df

    # Only get rows that correspond to 2021
    year2021 = df["Start_Time"].dt.year == int(2021)
    specifed_year = df[year2021]

    # Only get rows that have a severity of 4
    severity_4 = specifed_year["Severity"] == int(4)
    specifed_severity = specifed_year[severity_4]


    # 
    avg_temp = specifed_severity["Temperature(F)"].mean()
    avg_hummid = specifed_severity["Humidity(%)"].mean()

    if (pd.isna(avg_temp) == True):
        print("No tempature recordings for this year and or severity")
    
    if (pd.isna(avg_hummid) == True):
        print("No humidity recordings for this year and or severity")

    if ((pd.isna(avg_temp) == False) and (pd.isna(avg_hummid) == False)):
        print("What was the average humidity and average temperature of all accidents of severity 4 that occurred in 2021?")
        print("Average temperature: " + str(avg_temp) + "\nAverage humidity: " + str(avg_hummid))




avgerage_humidity_temp()

What was the average humidity and average temperature of all accidents of severity 4 that occurred in 2021?
Average temperature: 57.804559109383284
Average humidity: 66.95750708215297

In [29]:
# 7. What are the 3 most common weather conditions (weather_conditions) when accidents occurred?

def common_conditions():
    global df

    top_conditions = df["Weather_Condition"].value_counts()[:3]

    print("What are the 3 most common weather conditions (weather_conditions) when accidents occurred?")
    print(top_conditions.to_string())


common_conditions()

What are the 3 most common weather conditions (weather_conditions) when accidents occurred?
Fair             237116
Mostly Cloudy     78361
Cloudy            73463

In [30]:
# 8. What was the maximum visibility of all accidents of severity 2 that occurred in the state of New Hampshire?

def max_visibility():
    global df

    # Only get rows that correspond to New Hampshire
    new_hampshire = df["State"] == "NH"
    specfied_state = df[new_hampshire]

    # Only ger rows that have a Severity of 2
    severity = specfied_state["Severity"] == int(2)
    severity_2 = specfied_state[severity]

    # Get the max Visibility from the new constructed df
    max_vis = severity_2["Visibility(mi)"].max()

    print("What was the maximum visibility of all accidents of severity 2 that occurred in the state of New Hampshire?")
    print(max_vis)

    

max_visibility()

What was the maximum visibility of all accidents of severity 2 that occurred in the state of New Hampshire?
130.0

In [31]:
# 9. How many accidents of each severity were recorded in Bakersfield?

def bakersfield_severity_count():
    global df

    # Only get rows that belong to Bako
    bakersfield = df["City"] == "Bakersfield"
    city = df[bakersfield]

    # Get the types of severity accidents and the total number of them
    severity = city["Severity"].value_counts().index.tolist()
    severity_count = city["Severity"].value_counts().tolist()


    print("How many accidents of each severity were recorded in Bakersfield?")
    for i in range (len(severity)):
        print("Severity " + str(severity[i]) + " had " + str(severity_count[i]) + " accidents recorded")


bakersfield_severity_count()

How many accidents of each severity were recorded in Bakersfield?
Severity 2 had 2250 accidents recorded
Severity 3 had 26 accidents recorded
Severity 4 had 20 accidents recorded

In [33]:
# 10. What was the longest accident (in hours) recorded in Florida in the Spring (March, April, and May) of 2020?

def longest_accident():
    global df
    
    # Only get rows that correspond to 2020
    year2020 = df["Start_Time"].dt.year == int(2020)
    specifed_year = df[year2020]

    # Only get rows that correspond to Florida
    florida = specifed_year["State"] == "FL"
    state = specifed_year[florida]

    # Only get rows that correspond to March, April, and May
    specified_months = state.loc[
        (state['Start_Time'].dt.month == int(3)) | 
        (state['Start_Time'].dt.month == int(4)) | 
        (state['Start_Time'].dt.month == int(5))]

    # Find the longest accident
    # The longest accident will have the greatest differnce between Start_Time
    # and End_time

    accident_len = specified_months["End_Time"] - specified_months["Start_Time"]
    
    # longest_acc = accident_len.idxmax()
    longest_acc = accident_len.max()
    longest_acc = longest_acc / pd.Timedelta(hours = 1)
    # print(accident_len)


    print("10. What was the longest accident (in hours) recorded in Florida in the Spring (March, April, and May) of 2022?")
    print(longest_acc)
    # print(type(longest_acc))



longest_accident()

10. What was the longest accident (in hours) recorded in Florida in the Spring (March, April, and May) of 2022?
95.98777777777778